# active spring boot profile
spring:
   profiles:
      active: development

---
# common spring boot configuration
spring:
   # mvc
   mvc:
      view:
         prefix: /WEB-INF/views/
         suffix: .jsp
   # message resource(Internationalization)
   messages:
      # always-message-format: true
      basename: messages/messages_ko
      encoding: UTF-8
   # multipart
   servlet:
      multipart:
         enabled: true
         max-file-size: 50MB
         max-request-size: 50MB
   # AOP
   aop:
      auto: true
      proxy-target-class: true


---
# development profile - spring boot configuration
spring:
   config:
      activate:
         on-profile: development

   # devtools enabled
   devtools:
      livereload:
         enabled: true
      remote:
         restart:
            enabled: true
   # datasource
   datasource:
      driver-class-name: org.mariadb.jdbc.Driver
      url: jdbc:mysql://localhost:3306/webdb?characterEncoding=utf8
      username: webdb
      password: webdb


---
# production profile - spring boot configuration
spring:
   config:
      activate:
         on-profile: production

   # datasource
   datasource:
      driver-class-name: org.mariadb.jdbc.Driver
      url: jdbc:mysql://localhost:3306/webdb?characterEncoding=utf8
      username: webdb
      password: webdb


---
# server
server:
   port: 8080
   servlet:
      context-path: /mysite06
      encoding:
         charset: UTF-8
         enabled: true


---
# mybatis
mybatis:
   config-location: classpath:mybatis/configuration.xml